version: "1"
services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= true
      - MYSQL_DATABASE=wer_sitzt_wo_db
    ports:
      - '3306:3306'
  wer-sitzt-wo:
    build: ./
    container_name: wer-sitzt-wo
    ports:
      - '8080:8080'
    image: wer-sitzt-wo:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/wer_sitzt_wo_db?autoReconnect=true&useSSL=false
      DLL_AUTO: update
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD:
      DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SQL_DIALECT: com.mysql.cj.jdbc.Driver
    depends_on:
      - docker-mysql